settings = {
        "username": "infiltration_bot",
        "password": "Wouldn't you like to know",
        "delay": 15,
        "suspicious_subs": [
            "anarchism",
            "anarcho_capitalism",
            "anarchy101",
            "antipozi",
            "beatingcripples",
            "beatingniggers",
            "beatingwomen2",
            "beatingtrannies",
            "coontown",
            "conservative",
            "conspiracy",
            "darkenlightenment",
            "european",
            "fatlogic",
            "fatpeoplehate",
            "gendercritical",
            "gender_critical",
            "greatapes",
            "hbd",
            "killingwomen",
            "kotakuinaction",
            "libertarian",
            "mensrights",
            "metanarchism",
            "monarchism",
            "nationalsocialism",
            "nazi",
            "new_right",
            "polistan",
            "rapingwomen",
            "sjsucks",
            "sjwhate",
            "srssucks",
            "strugglefucking",
            "theredpill",
            "trans_fags",
            "tumblrinaction",
            "whiterights",
            "wikiinaction",
            ],
        }

try:
    from local_config import local_settings
    settings.update(local_settings)
except ImportError as e:
    pass
